spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  web:
    resources:
      static-locations: classpath:/static/,
      desktopPath: classpath:/C:/Users/sinan.aydin/OneDrive - Scale Focus AD/Desktop/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  swagger-ui:
    path: /swagger-ui
cloud:
  aws:
    s3:
      bucket: testbucketscalefocus
    region:
      static: eu-north-1
    credentials:
      access-key: AKIAZQ3DT66OUN6GQ3G5
      secret-key: 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
#logging:
#  level:
#    org:
#      springframework: DEBUG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: { hostname: localhost }
server:
  port: 9090
