spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


